import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex">
          <div className=" bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
            {/* Sidebar */}
          </div>
          <div className=" bg-[#343541] flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
